name: Deploy to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: your-gcp-project-id
  REGION: us-central1
  SERVICE_NAME: react-cloud-run-app

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        IMAGE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/react-repo/${{ env.SERVICE_NAME }}
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/react-repo/${{ env.SERVICE_NAME }} \
          --platform=managed \
          --region=${{ env.REGION }} \
          --allow-unauthenticated
